using System.Collections.Frozen;
using System.Globalization;

namespace Chat.Localization;

public sealed class TextCatalog : ITextCatalog
{
    public string Get(Locale locale, string key, params object[] args)
    {
        var template = Lookup(locale, key) ?? Lookup(Locale.English, key)
            ?? throw new InvalidOperationException("Missing text key: " + key);
        return args.Length == 0 ? template : string.Format(CultureInfo.CurrentCulture, template, args);
    }

    public IReadOnlyCollection<string> Keys => English.Keys;

    public bool SameKeys() =>
        Keys.Count == Chinese.Count && Keys.Count == Japanese.Count &&
        Keys.All(Chinese.ContainsKey) && Keys.All(Japanese.ContainsKey);

    private static string? Lookup(Locale locale, string key) =>
        Table(locale).TryGetValue(key, out var value) ? value : null;

    private static FrozenDictionary<string, string> Table(Locale locale) => locale.Code switch
    {
        "zh-Hans" => Chinese,
        "ja" => Japanese,
        _ => English
    };

    private static FrozenDictionary<string, string> Map(params (string Key, string Value)[] pairs) =>
        pairs.ToFrozenDictionary(item => item.Key, item => item.Value, StringComparer.Ordinal);

    private static readonly FrozenDictionary<string, string> English = Map(
        ("PageParticipants", "In this conversation"),
        ("Settings", "Settings"),
        ("Language", "Language"),
        ("CloseSettings", "Close settings"),
        ("AddInstance", "Add instance"),
        ("Instances", "Instances"),
        ("ConnectCommunity", "Connect to your community"),
        ("InstanceAddress", "Instance address"),
        ("InstanceAddressPlaceholder", "chat.example.com or 192.168.x.x:8080"),
        ("ActionStatus", "Status"),
        ("SignIn", "Sign in"),
        ("Register", "Sign up"),
        ("Username", "Username"),
        ("DisplayName", "Display name (sign up)"),
        ("DisplayNameField", "Display name"),
        ("Password", "Password"),
        ("Channels", "Channels"),
        ("ChannelList", "Channel list"),
        ("NewCommunity", "New community name"),
        ("CreateCommunity", "Create community"),
        ("InviteCode", "Invite code"),
        ("JoinCommunity", "Join community"),
        ("SignOut", "Sign out"),
        ("SignedOut", "Signed out"),
        ("Workspace", "Workspace"),
        ("NotConnected", "No instance connected"),
        ("Voice", "Voice"),
        ("InviteHintEmpty", "Create or join a community to start chatting."),
        ("InviteHint", "Invite {0}"),
        ("Messages", "Messages"),
        ("Sending", "Sending"),
        ("SendFailed", "Couldn’t send"),
        ("RetrySend", "Retry"),
        ("Image", "Image"),
        ("SendMessage", "Send a message"),
        ("Send", "Send"),
        ("MessageInput", "Message"),
        ("PickImages", "Send images"),
        ("LeaveVoice", "Leave"),
        ("Mute", "Mute"),
        ("Unmute", "Unmute"),
        ("Deafen", "Deafen"),
        ("Undeafen", "Undeafen"),
        ("VoiceConnected", "Voice connected"),
        ("VoiceJoinHint", "Select a voice channel to join"),
        ("VoiceMediaError", "In the channel, audio not connected: {0}"),
        ("AudioQuality", "Audio quality"),
        ("ChannelQualityCap", "Channel maximum"),
        ("QualityStandard", "Standard"),
        ("QualityStandardDetail", "48 kHz mono · 64 kbps"),
        ("QualityHigh", "High"),
        ("QualityHighDetail", "48 kHz stereo · 128 kbps"),
        ("QualityVeryHigh", "Very high"),
        ("QualityVeryHighDetail", "48 kHz stereo · 384 kbps"),
        ("QualityStudio", "Studio"),
        ("QualityStudioDetail", "48 kHz stereo · 510 kbps · Opus maximum"),
        ("InputDevice", "Input device"),
        ("OutputDevice", "Output device"),
        ("DefaultDevice", "System default"),
        ("DevicesUnavailable", "Couldn’t list audio devices: {0}"),
        ("MutedSuffix", " · muted"),
        ("DeafenedSuffix", " · deafened"),
        ("CacheLoadFailed", "Couldn’t load local cache: {0}"),
        ("Discovering", "Finding instance…"),
        ("InstanceSaved", "Instance saved. Sign in or sign up."),
        ("NeedInstance", "Add an instance first."),
        ("Registering", "Signing up…"),
        ("SigningIn", "Signing in…"),
        ("NeedSignIn", "Sign in first."),
        ("NoInstanceSelected", "No instance selected."),
        ("Cancelled", "Cancelled."),
        ("ImagesSelected", "{0} image(s) selected"),
        ("ProtocolIncompatible", "This instance uses an incompatible protocol version."),
        ("InstanceAddressConflict", "This instance was already added from a different address."),
        ("TooManyInstances", "You can add up to 32 instances."),
        ("InvalidInstanceAddress", "Enter an instance domain or HTTPS address. HTTP is allowed on this computer and LAN."),
        ("DiscoveryEmpty", "Instance discovery returned an empty response."),
        ("DiscoveryIdentityInvalid", "Instance identity is invalid."),
        ("DiscoveryOriginMismatch", "API and Gateway must share the instance origin."),
        ("DiscoveryInsecureEndpoint", "Instance endpoints must use a secure connection."),
        ("SelectChannel", "Select a channel"),
        ("MessageToChannel", "Message #{0}"),
        ("NoMatchingMessages", "No matching messages"),
        ("StillQuiet", "It’s quiet here"),
        ("DesignPreview", "Design preview"),
        ("Offline", "Offline"),
        ("NotSignedIn", "Not signed in"),
        ("Online", "Online"),
        ("OnlineCount", "Online — {0}"),
        ("ClipboardUnavailable", "Clipboard unavailable"),
        ("ClipboardFailed", "Couldn’t copy to the clipboard"),
        ("WindowTitlePreview", "{0} · design preview"),
        ("ChannelFallback", "Channel"),
        ("NotImplemented", "Not implemented yet"),
        ("Mic", "Microphone"),
        ("Headphones", "Headphones"),
        ("MicUnavailable", "Microphone · Not implemented yet"),
        ("HeadphonesUnavailable", "Headphones · Not implemented yet"),
        ("SettingsUnavailable", "Settings · Not implemented yet"),
        ("TextChannels", "Text channels"),
        ("VoiceChannels", "Voice channels"),
        ("ExpandTextChannels", "Expand or collapse text channels"),
        ("ExpandVoiceChannels", "Expand or collapse voice channels"),
        ("SearchMessages", "Search messages"),
        ("SearchShortcut", "Search messages · ⌘ F / Ctrl F"),
        ("Members", "Members"),
        ("ToggleMembers", "Toggle member list"),
        ("CloseSearch", "Close search"),
        ("MessageTimeline", "Message timeline"),
        ("CopyText", "Copy text"),
        ("CopyMessage", "Copy message"),
        ("ReactionUnavailable", "Reaction (not implemented yet)"),
        ("AddAttachment", "Add attachment"),
        ("Emoji", "Emoji"),
        ("CloseTab", "Close tab"),
        ("CloseChannelTab", "Close channel tab"),
        ("SearchInChannel", "Search this channel"),
        ("SearchContent", "Search message content"),
        ("ManageInstances", "Manage instances"),
        ("CloseAddInstance", "Close add instance"),
        ("CloseNotice", "Dismiss notice"),
        ("DropFiles", "Drop files here to send"),
        ("DownloadLocal", "Download"),
        ("DownloadFile", "Download file"),
        ("File", "File"),
        ("AddFile", "Add file"),
        ("SendMessageOrDrop", "Send a message, or drop files"),
        ("PickFiles", "Send files"),
        ("SaveFile", "Save file"),
        ("RemoveFile", "Remove"),
        ("Downloading", "Downloading"),
        ("PendingPrefix", "Queued"),
        ("PendingFiles", "Queued: {0}"),
        ("ListSeparator", ", "),
        ("FileLimitHint", "Add file · max {0}, up to {1} per message"),
        ("FileTooLarge", "{0} exceeds the {1} limit"),
        ("TooManyFiles", "Up to {0} files per message"),
        ("FileSaved", "Saved {0}"),
        ("Profile", "Profile"),
        ("ChangeAvatar", "Change avatar"),
        ("RemoveAvatar", "Remove avatar"),
        ("SaveProfile", "Save"),
        ("ProfileSaved", "Profile saved"),
        ("PickAvatar", "Choose avatar"),
        ("InvalidAvatar", "Avatar must be a JPEG, PNG, GIF, or WebP image."),
        ("BlockedWord", "Message contains a blocked word."),
        ("CooldownWait", "Wait {0} seconds before sending another message."),
        ("InvalidCooldown", "Message cooldown must be an integer from 0 to 600 seconds."),
        ("ModerationSaved", "Moderation settings saved."),
        ("ChatBehavior", "Chat"),
        ("GeneralSettings", "General"),
        ("SendShortcut", "Send shortcut"),
        ("MessageDensity", "Message density"),
        ("ComfortableLayout", "Comfortable"),
        ("Appearance", "Appearance"),
        ("EnterToSend", "Enter to send"),
        ("CtrlEnterToSend", "Ctrl / ⌘ Enter to send"),
        ("CompactLayout", "Compact layout"),
        ("ReduceMotion", "Reduce motion"),
        ("Moderation", "Moderation"),
        ("BlockedWordsHint", "Blocked words, one per line"),
        ("CooldownSeconds", "Cooldown (seconds)"),
        ("SaveModeration", "Save moderation"));

    private static readonly FrozenDictionary<string, string> Chinese = Map(
        ("PageParticipants", "本页参与者"),
        ("Settings", "设置"),
        ("Language", "语言"),
        ("CloseSettings", "关闭设置"),
        ("AddInstance", "添加实例"),
        ("Instances", "实例列表"),
        ("ConnectCommunity", "连接你的社区"),
        ("InstanceAddress", "实例地址"),
        ("InstanceAddressPlaceholder", "chat.example.com 或 192.168.x.x:8080"),
        ("ActionStatus", "操作状态"),
        ("SignIn", "登录"),
        ("Register", "注册"),
        ("Username", "用户名"),
        ("DisplayName", "显示名（注册）"),
        ("DisplayNameField", "显示名"),
        ("Password", "密码"),
        ("Channels", "频道"),
        ("ChannelList", "频道列表"),
        ("NewCommunity", "新社区名称"),
        ("CreateCommunity", "创建社区"),
        ("InviteCode", "邀请码"),
        ("JoinCommunity", "加入社区"),
        ("SignOut", "退出账号"),
        ("SignedOut", "未登录"),
        ("Workspace", "工作空间"),
        ("NotConnected", "尚未连接实例"),
        ("Voice", "语音"),
        ("InviteHintEmpty", "创建或加入一个社区后即可聊天。"),
        ("InviteHint", "邀请码 {0}"),
        ("Messages", "消息"),
        ("Sending", "发送中"),
        ("SendFailed", "发送失败"),
        ("RetrySend", "重试"),
        ("Image", "图片"),
        ("SendMessage", "发送消息"),
        ("Send", "发送"),
        ("MessageInput", "消息输入"),
        ("PickImages", "发送图片"),
        ("LeaveVoice", "离开"),
        ("Mute", "静音"),
        ("Unmute", "取消静音"),
        ("Deafen", "耳聋"),
        ("Undeafen", "取消耳聋"),
        ("VoiceConnected", "语音已连接"),
        ("VoiceJoinHint", "点击语音频道加入"),
        ("VoiceMediaError", "已进入频道，音频未接通：{0}"),
        ("AudioQuality", "音质"),
        ("ChannelQualityCap", "频道上限"),
        ("QualityStandard", "标准"),
        ("QualityStandardDetail", "48 kHz 单声道 · 64 kbps"),
        ("QualityHigh", "高"),
        ("QualityHighDetail", "48 kHz 立体声 · 128 kbps"),
        ("QualityVeryHigh", "很高"),
        ("QualityVeryHighDetail", "48 kHz 立体声 · 384 kbps"),
        ("QualityStudio", "最高"),
        ("QualityStudioDetail", "48 kHz 立体声 · 510 kbps · Opus 上限"),
        ("InputDevice", "输入设备"),
        ("OutputDevice", "输出设备"),
        ("DefaultDevice", "系统默认"),
        ("DevicesUnavailable", "无法列出音频设备：{0}"),
        ("MutedSuffix", " · 静音"),
        ("DeafenedSuffix", " · 耳聋"),
        ("CacheLoadFailed", "本地缓存加载失败：{0}"),
        ("Discovering", "正在发现实例…"),
        ("InstanceSaved", "已保存实例。请登录或注册。"),
        ("NeedInstance", "请先添加实例。"),
        ("Registering", "正在注册…"),
        ("SigningIn", "正在登录…"),
        ("NeedSignIn", "请先登录。"),
        ("NoInstanceSelected", "没有选中的实例。"),
        ("Cancelled", "已取消。"),
        ("ImagesSelected", "已选择 {0} 张图片"),
        ("ProtocolIncompatible", "实例协议版本不兼容。"),
        ("InstanceAddressConflict", "此实例已通过另一个地址添加。"),
        ("TooManyInstances", "最多可添加 32 个实例。"),
        ("InvalidInstanceAddress", "请输入实例域名或 HTTPS 地址；本机和局域网开发可使用 HTTP。"),
        ("DiscoveryEmpty", "实例发现响应为空。"),
        ("DiscoveryIdentityInvalid", "实例身份无效。"),
        ("DiscoveryOriginMismatch", "API 和 Gateway 必须与实例同源。"),
        ("DiscoveryInsecureEndpoint", "实例端点必须使用安全连接。"),
        ("SelectChannel", "选择一个频道"),
        ("MessageToChannel", "发消息到 #{0}"),
        ("NoMatchingMessages", "没有匹配的消息"),
        ("StillQuiet", "这里还很安静"),
        ("DesignPreview", "设计预览"),
        ("Offline", "离线"),
        ("NotSignedIn", "尚未登录"),
        ("Online", "在线"),
        ("OnlineCount", "在线 — {0}"),
        ("ClipboardUnavailable", "剪贴板不可用"),
        ("ClipboardFailed", "无法复制到剪贴板"),
        ("WindowTitlePreview", "{0} · 设计预览"),
        ("ChannelFallback", "频道"),
        ("NotImplemented", "尚未实现"),
        ("Mic", "麦克风"),
        ("Headphones", "耳机"),
        ("MicUnavailable", "麦克风 · 尚未实现"),
        ("HeadphonesUnavailable", "耳机 · 尚未实现"),
        ("SettingsUnavailable", "设置 · 尚未实现"),
        ("TextChannels", "文字频道"),
        ("VoiceChannels", "语音频道"),
        ("ExpandTextChannels", "展开或收起文字频道"),
        ("ExpandVoiceChannels", "展开或收起语音频道"),
        ("SearchMessages", "搜索消息"),
        ("SearchShortcut", "搜索消息 · ⌘ F / Ctrl F"),
        ("Members", "成员"),
        ("ToggleMembers", "切换成员栏"),
        ("CloseSearch", "关闭搜索"),
        ("MessageTimeline", "消息时间线"),
        ("CopyText", "复制文本"),
        ("CopyMessage", "复制消息"),
        ("ReactionUnavailable", "回应（尚未实现）"),
        ("AddAttachment", "添加附件"),
        ("Emoji", "表情"),
        ("CloseTab", "关闭标签"),
        ("CloseChannelTab", "关闭频道标签"),
        ("SearchInChannel", "搜索此频道"),
        ("SearchContent", "搜索消息内容"),
        ("ManageInstances", "管理实例"),
        ("CloseAddInstance", "关闭添加实例"),
        ("CloseNotice", "关闭提示"),
        ("DropFiles", "放到这里发送文件"),
        ("DownloadLocal", "下载到本地"),
        ("DownloadFile", "下载文件"),
        ("File", "文件"),
        ("AddFile", "添加文件"),
        ("SendMessageOrDrop", "发送消息，或拖入文件"),
        ("PickFiles", "发送文件"),
        ("SaveFile", "保存文件"),
        ("RemoveFile", "移除"),
        ("Downloading", "正在下载"),
        ("PendingPrefix", "待发送"),
        ("PendingFiles", "待发送：{0}"),
        ("ListSeparator", "、"),
        ("FileLimitHint", "添加文件 · 最大 {0}，每条最多 {1} 个"),
        ("FileTooLarge", "{0} 超过 {1} 上限"),
        ("TooManyFiles", "每条最多 {0} 个文件"),
        ("FileSaved", "已保存 {0}"),
        ("Profile", "资料"),
        ("ChangeAvatar", "更换头像"),
        ("RemoveAvatar", "移除头像"),
        ("SaveProfile", "保存"),
        ("ProfileSaved", "资料已保存"),
        ("PickAvatar", "选择头像"),
        ("InvalidAvatar", "头像需为 JPEG、PNG、GIF 或 WebP 图片。"),
        ("BlockedWord", "消息包含屏蔽词。"),
        ("CooldownWait", "请等待 {0} 秒后再发送消息。"),
        ("InvalidCooldown", "发言冷却时间须为 0 到 600 秒的整数。"),
        ("ModerationSaved", "管理设置已保存。"),
        ("ChatBehavior", "聊天"),
        ("GeneralSettings", "通用"),
        ("SendShortcut", "发送快捷键"),
        ("MessageDensity", "消息间距"),
        ("ComfortableLayout", "宽松布局"),
        ("Appearance", "外观"),
        ("EnterToSend", "Enter 发送"),
        ("CtrlEnterToSend", "Ctrl / ⌘ + Enter 发送"),
        ("CompactLayout", "紧凑布局"),
        ("ReduceMotion", "减少动效"),
        ("Moderation", "管理"),
        ("BlockedWordsHint", "屏蔽词，每行一个"),
        ("CooldownSeconds", "发言冷却（秒）"),
        ("SaveModeration", "保存管理设置"));

    private static readonly FrozenDictionary<string, string> Japanese = Map(
        ("PageParticipants", "この会話の参加者"),
        ("Settings", "設定"),
        ("Language", "言語"),
        ("CloseSettings", "設定を閉じる"),
        ("AddInstance", "インスタンスを追加"),
        ("Instances", "インスタンス"),
        ("ConnectCommunity", "コミュニティに接続"),
        ("InstanceAddress", "インスタンスアドレス"),
        ("InstanceAddressPlaceholder", "chat.example.com または 192.168.x.x:8080"),
        ("ActionStatus", "状態"),
        ("SignIn", "ログイン"),
        ("Register", "登録"),
        ("Username", "ユーザー名"),
        ("DisplayName", "表示名（登録）"),
        ("DisplayNameField", "表示名"),
        ("Password", "パスワード"),
        ("Channels", "チャンネル"),
        ("ChannelList", "チャンネル一覧"),
        ("NewCommunity", "新しいコミュニティ名"),
        ("CreateCommunity", "コミュニティを作成"),
        ("InviteCode", "招待コード"),
        ("JoinCommunity", "コミュニティに参加"),
        ("SignOut", "ログアウト"),
        ("SignedOut", "未ログイン"),
        ("Workspace", "ワークスペース"),
        ("NotConnected", "インスタンス未接続"),
        ("Voice", "ボイス"),
        ("InviteHintEmpty", "コミュニティを作成または参加するとチャットできます。"),
        ("InviteHint", "招待コード {0}"),
        ("Messages", "メッセージ"),
        ("Sending", "送信中"),
        ("SendFailed", "送信に失敗しました"),
        ("RetrySend", "再試行"),
        ("Image", "画像"),
        ("SendMessage", "メッセージを送信"),
        ("Send", "送信"),
        ("MessageInput", "メッセージ入力"),
        ("PickImages", "画像を送信"),
        ("LeaveVoice", "退出"),
        ("Mute", "ミュート"),
        ("Unmute", "ミュート解除"),
        ("Deafen", "スピーカーミュート"),
        ("Undeafen", "スピーカーミュート解除"),
        ("VoiceConnected", "ボイスに接続しました"),
        ("VoiceJoinHint", "ボイスチャンネルを選択して参加"),
        ("VoiceMediaError", "チャンネルに入りましたが、音声は未接続です：{0}"),
        ("AudioQuality", "音質"),
        ("ChannelQualityCap", "チャンネル上限"),
        ("QualityStandard", "標準"),
        ("QualityStandardDetail", "48 kHz モノラル · 64 kbps"),
        ("QualityHigh", "高"),
        ("QualityHighDetail", "48 kHz ステレオ · 128 kbps"),
        ("QualityVeryHigh", "非常に高い"),
        ("QualityVeryHighDetail", "48 kHz ステレオ · 384 kbps"),
        ("QualityStudio", "最高"),
        ("QualityStudioDetail", "48 kHz ステレオ · 510 kbps · Opus 最大"),
        ("InputDevice", "入力デバイス"),
        ("OutputDevice", "出力デバイス"),
        ("DefaultDevice", "システムのデフォルト"),
        ("DevicesUnavailable", "オーディオデバイスを列挙できません：{0}"),
        ("MutedSuffix", " · ミュート"),
        ("DeafenedSuffix", " · スピーカーミュート"),
        ("CacheLoadFailed", "ローカルキャッシュを読み込めませんでした：{0}"),
        ("Discovering", "インスタンスを検出しています…"),
        ("InstanceSaved", "インスタンスを保存しました。ログインまたは登録してください。"),
        ("NeedInstance", "先にインスタンスを追加してください。"),
        ("Registering", "登録しています…"),
        ("SigningIn", "ログインしています…"),
        ("NeedSignIn", "先にログインしてください。"),
        ("NoInstanceSelected", "インスタンスが選択されていません。"),
        ("Cancelled", "キャンセルしました。"),
        ("ImagesSelected", "{0} 枚の画像を選択しました"),
        ("ProtocolIncompatible", "このインスタンスのプロトコルバージョンは互換性がありません。"),
        ("InstanceAddressConflict", "このインスタンスは別のアドレスで追加済みです。"),
        ("TooManyInstances", "インスタンスは最大 32 件まで追加できます。"),
        ("InvalidInstanceAddress", "インスタンスのドメインまたは HTTPS アドレスを入力してください。このコンピュータと LAN では HTTP を利用できます。"),
        ("DiscoveryEmpty", "インスタンス検出の応答が空です。"),
        ("DiscoveryIdentityInvalid", "インスタンスの識別情報が無効です。"),
        ("DiscoveryOriginMismatch", "API と Gateway はインスタンスと同じオリジンである必要があります。"),
        ("DiscoveryInsecureEndpoint", "インスタンスのエンドポイントは安全な接続を使う必要があります。"),
        ("SelectChannel", "チャンネルを選択"),
        ("MessageToChannel", "#{0} に送信"),
        ("NoMatchingMessages", "一致するメッセージはありません"),
        ("StillQuiet", "まだ静かです"),
        ("DesignPreview", "デザインプレビュー"),
        ("Offline", "オフライン"),
        ("NotSignedIn", "未ログイン"),
        ("Online", "オンライン"),
        ("OnlineCount", "オンライン — {0}"),
        ("ClipboardUnavailable", "クリップボードを利用できません"),
        ("ClipboardFailed", "クリップボードにコピーできませんでした"),
        ("WindowTitlePreview", "{0} · デザインプレビュー"),
        ("ChannelFallback", "チャンネル"),
        ("NotImplemented", "未実装"),
        ("Mic", "マイク"),
        ("Headphones", "ヘッドフォン"),
        ("MicUnavailable", "マイク · 未実装"),
        ("HeadphonesUnavailable", "ヘッドフォン · 未実装"),
        ("SettingsUnavailable", "設定 · 未実装"),
        ("TextChannels", "テキストチャンネル"),
        ("VoiceChannels", "ボイスチャンネル"),
        ("ExpandTextChannels", "テキストチャンネルを展開または折りたたむ"),
        ("ExpandVoiceChannels", "ボイスチャンネルを展開または折りたたむ"),
        ("SearchMessages", "メッセージを検索"),
        ("SearchShortcut", "メッセージを検索 · ⌘ F / Ctrl F"),
        ("Members", "メンバー"),
        ("ToggleMembers", "メンバー一覧を切り替え"),
        ("CloseSearch", "検索を閉じる"),
        ("MessageTimeline", "メッセージタイムライン"),
        ("CopyText", "テキストをコピー"),
        ("CopyMessage", "メッセージをコピー"),
        ("ReactionUnavailable", "リアクション（未実装）"),
        ("AddAttachment", "添付を追加"),
        ("Emoji", "絵文字"),
        ("CloseTab", "タブを閉じる"),
        ("CloseChannelTab", "チャンネルタブを閉じる"),
        ("SearchInChannel", "このチャンネルを検索"),
        ("SearchContent", "メッセージ内容を検索"),
        ("ManageInstances", "インスタンスを管理"),
        ("CloseAddInstance", "追加画面を閉じる"),
        ("CloseNotice", "通知を閉じる"),
        ("DropFiles", "ここにドロップして送信"),
        ("DownloadLocal", "ダウンロード"),
        ("DownloadFile", "ファイルをダウンロード"),
        ("File", "ファイル"),
        ("AddFile", "ファイルを追加"),
        ("SendMessageOrDrop", "メッセージを送信、またはファイルをドロップ"),
        ("PickFiles", "ファイルを送信"),
        ("SaveFile", "ファイルを保存"),
        ("RemoveFile", "削除"),
        ("Downloading", "ダウンロード中"),
        ("PendingPrefix", "送信待ち"),
        ("PendingFiles", "送信待ち：{0}"),
        ("ListSeparator", "、"),
        ("FileLimitHint", "ファイルを追加 · 最大 {0}、1 件あたり {1} 個まで"),
        ("FileTooLarge", "{0} は上限 {1} を超えています"),
        ("TooManyFiles", "1 件あたり最大 {0} 個のファイル"),
        ("FileSaved", "{0} を保存しました"),
        ("Profile", "プロフィール"),
        ("ChangeAvatar", "アバターを変更"),
        ("RemoveAvatar", "アバターを削除"),
        ("SaveProfile", "保存"),
        ("ProfileSaved", "プロフィールを保存しました"),
        ("PickAvatar", "アバターを選択"),
        ("InvalidAvatar", "アバターは JPEG、PNG、GIF、または WebP 画像にしてください。"),
        ("BlockedWord", "メッセージに禁止ワードが含まれています。"),
        ("CooldownWait", "次のメッセージを送信するまで {0} 秒お待ちください。"),
        ("InvalidCooldown", "送信間隔は 0～600 秒の整数で指定してください。"),
        ("ModerationSaved", "管理設定を保存しました。"),
        ("ChatBehavior", "チャット"),
        ("GeneralSettings", "一般"),
        ("SendShortcut", "送信ショートカット"),
        ("MessageDensity", "メッセージの間隔"),
        ("ComfortableLayout", "ゆったり表示"),
        ("Appearance", "外観"),
        ("EnterToSend", "Enter で送信"),
        ("CtrlEnterToSend", "Ctrl / ⌘ + Enter で送信"),
        ("CompactLayout", "コンパクト表示"),
        ("ReduceMotion", "動きを減らす"),
        ("Moderation", "管理"),
        ("BlockedWordsHint", "禁止ワード（1行1語）"),
        ("CooldownSeconds", "送信間隔（秒）"),
        ("SaveModeration", "管理設定を保存"));
}
