<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Core/Chat.Core.csproj" />
    <ProjectReference Include="../Protocol/Chat.Protocol.csproj" />
    <ProjectReference Include="../Localization/Chat.Localization.csproj" />

  </ItemGroup>
</Project>
